base: &BASE
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  port: 5432
  username: postgres
  password: password

development:
  <<: *BASE
  database: ror_tut_development

test:
  <<: *BASE
  database: ror_tut_test
  min_messages: WARNING

production:
  <<: *BASE
  database: ror_tut_production